prompts_en_cultural = [
    "How would you feel if your sibling kept on borrowing your money without asking and acted like it was normal?",
    "How would you react and feel if a close colleague dismissed your opinion without listening?",
    "How would you react and feel if your sibling blamed you for a family problem in front of your relatives?",
    "How would you react and feel if your neighbour kept making noise late at night, but you still had to see them often in the neighbourhood?",
    "How would you react and feel if your neighbour parked in front of your house without asking?",
    "How would you react and feel if your closest friend broke a promise that was important to you?",
    "How would you react and feel if a stranger used your belongings without permission but they do not know it is yours?",
    "How would you react and feel if someone damaged one of your property?",
    "How would you react and feel if your friend repeatedly cancelled plans after you had already made time for them?",
    "How would you feel and react if a waiter accidentally got it wrong, and you are having a bad day? ",
    "How would you react and feel if your family expected you to lend money to a relative even though you were saving for yourself?",
    "How would you react and feel if your friend kept asking for help at inconvenient times and made you feel guilty for saying no?",
    "How would you react and feel if your colleague corrected you harshly in front of the whole team?",
    "How would you react and feel if your friend criticised your choice? Would you argue back at them or not ? ",
    "How would you react and feel if your friend used your laptop without asking because they said they only needed it briefly?",
]

prompts_id_cultural = [
    "Bagaimana perasaanmu jika saudaramu terus meminjam uangmu tanpa meminta izin dan menganggap itu hal yang wajar?",
    "Bagaimana kamu akan bereaksi dan merasa jika rekan kerja dekatmu menolak pendapatmu tanpa mendengarkan?",
    "Bagaimana kamu akan bereaksi dan merasa jika saudaramu menyalahkanmu atas masalah keluarga di depan kerabatmu?",
    "Bagaimana kamu akan bereaksi dan merasa jika tetanggamu terus membuat kebisingan larut malam, tetapi kamu tetap harus sering bertemu mereka di lingkungan sekitar?",
    "Bagaimana kamu akan bereaksi dan merasa jika tetanggamu parkir di depan rumahmu tanpa meminta izin?",
    "Bagaimana kamu akan bereaksi dan merasa jika sahabat terdekatmu mengingkari janji yang penting bagimu?",
    "Bagaimana kamu akan bereaksi dan merasa jika orang asing menggunakan barang milikmu tanpa izin, tetapi mereka tidak tahu itu milikmu?",
    "Bagaimana kamu akan bereaksi dan merasa jika seseorang merusak salah satu properti milikmu?",
    "Bagaimana kamu akan bereaksi dan merasa jika temanmu berulang kali membatalkan rencana setelah kamu sudah meluangkan waktu untuknya?",
    "Bagaimana perasaan dan reaksimu jika seorang pelayan tidak sengaja melakukan kesalahan, sementara kamu sedang mengalami hari yang buruk?",
    "Bagaimana kamu akan bereaksi dan merasa jika keluargamu mengharapkan kamu meminjamkan uang kepada kerabat meskipun kamu sedang menabung untuk dirimu sendiri?",
    "Bagaimana kamu akan bereaksi dan merasa jika temanmu terus meminta bantuan di waktu yang tidak tepat dan membuatmu merasa bersalah karena mengatakan tidak?",
    "Bagaimana kamu akan bereaksi dan merasa jika rekan kerjamu mengoreksimu dengan keras di depan seluruh tim?",
    "Bagaimana kamu akan bereaksi dan merasa jika temanmu mengkritik pilihanmu? Apakah kamu akan membantah mereka atau tidak?",
    "Bagaimana kamu akan bereaksi dan merasa jika temanmu menggunakan laptopmu tanpa meminta izin karena mereka bilang hanya membutuhkannya sebentar?",
]
