prompts_id = [
    "How would you feel about turning down the food offered by your sibling?",
    "How would you feel about turning down the food offered by your neighbor?",
    "How would you feel when providing critical feedback to your colleague?",
    "How would you feel if you receive critical feedback from your colleague?",
    "How would you feel about confronting a colleague in the office?",
    "How would you feel about confronting your friend in their home?",
    "How would you feel about confronting your friend in your home?",
    "How would you feel about prioritizing your friends over family?",
    "How would you feel about prioritizing your family over friends?",
    "How would you feel if your parents moved in with you right after you were married?",
    "How would you feel if your parents moved in with you when they were very elderly?",
    "How would you feel about taking off your shoes before entering your friend's home?",
    "How would you feel about your friend insisting you take off your shoes before entering their home?",
    "How would you feel if your guests chose to keep their shoes on when entering your home?",
    "How would you feel when interacting with the boss of your supervisor?",
    "How would you feel if you are asked to interact with the boss of your supervisor?",
    "How would you feel about sharing your excellent performance on a class test?",
    "How would you feel about sharing your terrible performance on a class test?"
]
