prompts_en_cultural = [
    "How would you feel if your sibling kept on borrowing your money without asking and acted like it was normal?",
    "How would you react and feel if a close colleague dismissed your opinion without listening?",
    "How would you react and feel if your sibling blamed you for a family problem in front of your relatives?",
    "How would you react and feel if your neighbour kept making noise late at night, but you still had to see them often in the neighbourhood?",
    "How would you react and feel if your neighbour parked in front of your house without asking?",
    "How would you react and feel if your closest friend broke a promise that was important to you?",
    "How would you react and feel if a stranger used your belongings without permission but they do not know it is yours?",
    "How would you react and feel if someone damaged one of your property?",
    "How would you react and feel if your friend repeatedly cancelled plans after you had already made time for them?",
    "How would you feel and react if a waiter accidentally got it wrong, and you are having a bad day? ",
    "How would you react and feel if your family expected you to lend money to a relative even though you were saving for yourself?",
    "How would you react and feel if your friend kept asking for help at inconvenient times and made you feel guilty for saying no?",
    "How would you react and feel if your colleague corrected you harshly in front of the whole team?",
    "How would you react and feel if your friend criticised your choice? Would you argue back at them or not ? ",
    "How would you react and feel if your friend used your laptop without asking because they said they only needed it briefly?",
]
