fear_prompts_en = [
    "How would you feel and react if a police officer stopped you, questioned you, and started recording you, even though you had done nothing wrong?",
    "How would you feel and react if your parents found out you made a major life decision without asking them first?",
    "How would you feel and react if a senior colleague suddenly asked you to present your work in front of everyone without preparation?",
    "How would you feel and react if you accidentally sent a private message to the wrong group chat, and people had already seen it?",
    "How would you feel and react if your neighbour accused you of being rude in front of other neighbours, even though you did not mean anything bad?",
    "How would you feel and react if your boss asked why your work was delayed in front of the whole team?",
    "How would you feel and react if your family expected you to attend an important gathering, but you had already promised your friends you would go somewhere else?",
    "How would you feel and react if someone older than you corrected you harshly in public, even though you thought you were right?",
    "How would you feel and react if a stranger started following you on the street at night?",
    "How would you feel and react if you heard that your package might be lost after waiting for it for two weeks?",
    "How would you feel and react if you had to tell your parents that you failed an important exam or interview?",
    "How would you feel and react if your teacher or lecturer suddenly called your name and asked you to answer a difficult question in front of the class?",
    "How would you feel and react if your close friend became quiet after you said something, and you started worrying that you offended them?",
    "How would you feel and react if you were invited to join an important project, but you were afraid you might disappoint the people who trusted you?",
    "How would you feel and react if you had to complain to a waiter because they got your order wrong, but the restaurant was crowded and people could hear you?",
    "How would you feel and react if your younger sibling blamed you for a family problem in front of your parents?",
    "How would you feel and react if your manager sent you a short message saying, 'Come to my office now,' without explaining why?",
    "How would you feel and react if you had to reject food offered by an elderly neighbour because you did not want to eat it?",
    "How would you feel and react if someone used your belongings without asking, but they acted like it was normal?",
    "How would you feel and react if you had symptoms of illness before an important family or work event, and you were worried it might affect others?",
    "How would you feel and react if a group of people started laughing right after you made a mistake in public?",
    "How would you feel and react if you had to confront your friend for borrowing money repeatedly without asking properly?",
    "How would you feel and react if you were alone in a public place and felt like people were staring at you?",
    "How would you feel and react if you had to speak up against someone older or more powerful who was clearly wrong?",
    "How would you feel and react if your family found out about something personal you had been hiding because you were embarrassed?"
]
fear_prompts_id = [
    "Bagaimana perasaan dan reaksi Anda jika seorang polisi menghentikan Anda, menanyai Anda, lalu mulai merekam Anda, padahal Anda tidak melakukan kesalahan apa pun?",
    "Bagaimana perasaan dan reaksi Anda jika orang tua Anda mengetahui bahwa Anda membuat keputusan besar dalam hidup tanpa meminta pendapat mereka terlebih dahulu?",
    "Bagaimana perasaan dan reaksi Anda jika Anda pergi ke acara keluarga pasangan Anda lalu tanpa sengaja menyinggung seorang yang lebih tua di sana dan semua orang menjadi diam?",
    "Bagaimana perasaan dan reaksi Anda jika tetangga Anda mulai bergosip tentang sesuatu yang tidak Anda lakukan, lalu keluarga Anda mendengarnya?",
    "Bagaimana perasaan dan reaksi Anda jika seorang guru atau dosen mempertanyakan kejujuran Anda secara terbuka di depan seluruh kelas?",
    "Bagaimana perasaan dan reaksi Anda jika rekan satu tim menyalahkan Anda atas kegagalan kelompok meskipun itu bukan sepenuhnya kesalahan Anda?",
    "Bagaimana perasaan dan reaksi Anda jika seorang anggota keluarga yang lebih senior menanyakan hal yang sangat pribadi kepada Anda di depan banyak orang?",
    "Bagaimana perasaan dan reaksi Anda jika seorang kerabat yang lebih tua tiba-tiba menanyakan mengapa Anda belum menikah saat acara keluarga, padahal alasannya sangat sensitif?",
    "Bagaimana perasaan dan reaksi Anda jika dosen Anda menuduh Anda tidak menghormati mereka karena Anda mempertanyakan pendapat mereka di kelas?",
    "Bagaimana perasaan dan reaksi Anda jika manajer Anda memberi isyarat bahwa Anda bersikap tidak sopan karena Anda tidak setuju dengan keputusan mereka?",
    "Bagaimana perasaan dan reaksi Anda jika Anda diharapkan menghadiri acara keluarga, tetapi Anda sudah memiliki rencana pribadi lain yang juga penting?",
    "Bagaimana perasaan dan reaksi Anda jika atasan Anda mengirim pesan samar yang berbunyi, \"Besok kita perlu membahas performa Anda\"?",
]
