in_store_retail_chatbot_prompts_300 = [
    "[Store navigation] I’m standing near the entrance. Which aisle has phone chargers?",
    "[Store navigation] Can you guide me from the bakery section to household cleaning products?",
    "[Store navigation] I’m by the customer-service desk. Where can I find travel-size toiletries?",
    "[Store navigation] Which floor has men’s formal shoes?",
    "[Store navigation] I’m near aisle 12, but I can’t find the pet-food section. Which way should I go?",
    "[Store navigation] Where is the nearest fitting room from the women’s jackets section?",
    "[Store navigation] I’ve just come in through the car-park entrance. How do I get to click and collect?",
    "[Store navigation] Which part of the store has printer ink and office supplies?",
    "[Store navigation] I’m in the homeware department. Where are the checkout tills from here?",
    "[Store navigation] Can you give me step-by-step directions to the baby-care aisle?",
    "[Finding a specific product] Do you sell USB-C to HDMI adapters in this store, and where would they be?",
    "[Finding a specific product] I’m looking for oat milk without added sugar. Which shelf should I check?",
    "[Finding a specific product] Where can I find black school trousers for an eight-year-old?",
    "[Finding a specific product] Do you stock replacement filters for a Brita water jug here?",
    "[Finding a specific product] I need fragrance-free laundry detergent. Can you point me to a suitable product?",
    "[Finding a specific product] Where are the gluten-free birthday cakes kept?",
    "[Finding a specific product] I’m trying to find a 30-watt fast charger for an iPhone. Do you have one in store?",
    "[Finding a specific product] Do you sell plain white pillowcases individually rather than as a set?",
    "[Finding a specific product] I need a padlock that will fit a gym locker. Which section should I visit?",
    "[Finding a specific product] Can you help me find a small sewing repair kit?",
    "[Live stock availability] The shelf is empty. Is there any more of this cereal in the stockroom?",
    "[Live stock availability] Do you have this jacket in a medium somewhere else in the store?",
    "[Live stock availability] The app says this coffee machine is in stock, but I can’t see it on display. Can you check?",
    "[Live stock availability] Are there any more size-six trainers available behind the counter?",
    "[Live stock availability] Can you check whether another branch nearby has this lamp in stock today?",
    "[Live stock availability] Is the last display model of this television available to buy?",
    "[Live stock availability] Do you have unopened boxes of this dinner set, or only the one on the shelf?",
    "[Live stock availability] The freezer section is out of this brand. Is a delivery expected later today?",
    "[Live stock availability] Can you tell me how many of these headphones are left in this store?",
    "[Live stock availability] Is this product reserved for someone, or can I take the last one showing in the cabinet?",
    "[Product comparison] I’m looking at these two vacuum cleaners. Which one is better for pet hair?",
    "[Product comparison] What is the practical difference between these two coffee machines?",
    "[Product comparison] Which of these laptops would be better for university work and light video editing?",
    "[Product comparison] I’m comparing these two moisturisers. Which one is better for very dry skin?",
    "[Product comparison] Which of these suitcases is more durable for frequent flights?",
    "[Product comparison] Can you compare the battery life of these two wireless headphones?",
    "[Product comparison] Which of these frying pans is easier to maintain over time?",
    "[Product comparison] I’m deciding between these two baby carriers. Which gives better back support?",
    "[Product comparison] Which of these mattresses is more suitable for someone who sleeps on their side?",
    "[Product comparison] Can you explain why this television costs £200 more than the one beside it?",
    "[Size and fit] I usually wear a UK 10, but this brand looks small. What size should I try?",
    "[Size and fit] These jeans fit at the waist but feel tight around the thighs. Is there a better cut?",
    "[Size and fit] Does this shoe style normally run large or small?",
    "[Size and fit] I’m buying this coat as a gift. How can I estimate the right size?",
    "[Size and fit] Do you have a fitting guide for this sports bra?",
    "[Size and fit] The medium shirt fits my shoulders but is too loose at the waist. Is there a slim-fit version?",
    "[Size and fit] Would this helmet fit a child with a head measurement of 54 centimetres?",
    "[Size and fit] I need trousers with a shorter leg length. Which versions come in petite sizing?",
    "[Size and fit] Is there a wider-fit version of these walking shoes?",
    "[Size and fit] Can you suggest a school uniform size for a child who is 138 centimetres tall?",
    "[Style, colour and appearance] Does this blazer come in a darker navy?",
    "[Style, colour and appearance] Which colour of this sofa would hide marks best in a home with children?",
    "[Style, colour and appearance] Can you suggest a shirt in this store that would match these trousers?",
    "[Style, colour and appearance] I like this dress, but do you have something similar with sleeves?",
    "[Style, colour and appearance] Which of these paint colours would make a small room feel brighter?",
    "[Style, colour and appearance] Can you show me trainers with the same shape but less visible branding?",
    "[Style, colour and appearance] I need an outfit for a smart-casual dinner. What could I pair with this skirt?",
    "[Style, colour and appearance] Does this lipstick shade suit warm or cool undertones?",
    "[Style, colour and appearance] I like this rug pattern. Is there a more neutral version in the same size?",
    "[Style, colour and appearance] Can you suggest a handbag that matches these shoes without being exactly the same colour?",
    "[Ingredients and allergens] I’m holding this sauce. Does it contain peanuts or traces of peanuts?",
    "[Ingredients and allergens] Is this bread made in a facility that handles sesame?",
    "[Ingredients and allergens] Which of these ready meals is safe for someone with a dairy allergy?",
    "[Ingredients and allergens] Does this shampoo contain sulphates or added fragrance?",
    "[Ingredients and allergens] Can you check whether this chocolate contains gelatine?",
    "[Ingredients and allergens] Is this product suitable for someone with a severe egg allergy?",
    "[Ingredients and allergens] I can’t read the small label. Does this snack contain soy?",
    "[Ingredients and allergens] Does this face cream include retinol or any retinoid ingredient?",
    "[Ingredients and allergens] Which of these protein bars is nut-free?",
    "[Ingredients and allergens] Can you explain what the allergen warning on this package means?",
    "[Dietary preferences] Which ready meals in this fridge are vegan and high in protein?",
    "[Dietary preferences] I need a halal lunch option that can be eaten cold. What do you have?",
    "[Dietary preferences] Can you suggest a low-salt soup from this aisle?",
    "[Dietary preferences] Which yoghurts here are lactose-free but not plant-based?",
    "[Dietary preferences] I’m looking for a vegetarian alternative to this chicken product. What is closest?",
    "[Dietary preferences] Which breakfast cereal has the least added sugar?",
    "[Dietary preferences] Can you find me a gluten-free pasta that cooks similarly to regular pasta?",
    "[Dietary preferences] I need kosher snacks for a meeting. Which products are clearly certified?",
    "[Dietary preferences] Which drinks here are caffeine-free and sugar-free?",
    "[Dietary preferences] Can you suggest a high-fibre meal I can prepare in under ten minutes?",
    "[Freshness and expiry] This pack expires tomorrow. Is there a fresher one available?",
    "[Freshness and expiry] How can I tell whether this avocado is ready to eat tonight?",
    "[Freshness and expiry] These strawberries look soft. Was this batch delivered today?",
    "[Freshness and expiry] Can you help me choose a ripe melon from this display?",
    "[Freshness and expiry] Is this reduced chicken safe to freeze today and cook next week?",
    "[Freshness and expiry] Where can I find the use-by date on this package?",
    "[Freshness and expiry] This milk has only two days left. Do you have a later date in the back?",
    "[Freshness and expiry] How long should this bakery bread stay fresh after I buy it?",
    "[Freshness and expiry] Is the fish at this counter fresh or previously frozen?",
    "[Freshness and expiry] Can I still buy this product if the best-before date is today?",
    "[Prices and promotions] The shelf label says £12, but the app says £9. Which price will I pay?",
    "[Prices and promotions] Is this buy-one-get-one-free offer applied automatically at checkout?",
    "[Prices and promotions] Does the promotion include all flavours or only the one shown on the sign?",
    "[Prices and promotions] Why is this item more expensive in store than it was online this morning?",
    "[Prices and promotions] Is there a multibuy discount if I purchase three of these?",
    "[Prices and promotions] The promotional sign is still up, but the offer date ended yesterday. Will it be honoured?",
    "[Prices and promotions] Can you check whether this yellow sticker is the final reduced price?",
    "[Prices and promotions] Does the student discount apply to this product in store?",
    "[Prices and promotions] If I buy this television today, is installation included in the advertised price?",
    "[Prices and promotions] Can this in-store price be matched to another retailer’s current offer?",
    "[Loyalty programme] How do I add today’s purchase to my loyalty account before I pay?",
    "[Loyalty programme] My loyalty app is not showing the member price for this item. What should I do?",
    "[Loyalty programme] Can I use my points to pay for part of this basket?",
    "[Loyalty programme] I forgot my loyalty card. Can the cashier find my account using my phone number?",
    "[Loyalty programme] Why did I not receive points for the purchase I made in this store yesterday?",
    "[Loyalty programme] Is there a member-only offer on this product today?",
    "[Loyalty programme] Can I combine a loyalty reward with the current promotion?",
    "[Loyalty programme] My app says I have a £5 reward, but it is not appearing at checkout. Can you help?",
    "[Loyalty programme] How many points would I earn if I buy this appliance today?",
    "[Loyalty programme] Can I sign up for the loyalty programme at the till and use the discount immediately?",
    "[Coupons and vouchers] I have a paper coupon for this item. Can I use it at self-checkout?",
    "[Coupons and vouchers] Why is this voucher being rejected when it is still within the expiry date?",
    "[Coupons and vouchers] Can I use two different coupons on the same purchase?",
    "[Coupons and vouchers] Does this gift voucher work in this branch?",
    "[Coupons and vouchers] I left my voucher at home, but it is visible in my account. Can it still be used?",
    "[Coupons and vouchers] The barcode on my coupon is damaged. Is there another way to redeem it?",
    "[Coupons and vouchers] Can I use this online discount code while paying in store?",
    "[Coupons and vouchers] Does this £10 voucher require a minimum spend?",
    "[Coupons and vouchers] Can a promotional voucher be used to buy a gift card?",
    "[Coupons and vouchers] I returned the item I bought with a voucher. Will the voucher value be restored?",
    "[Self-checkout assistance] The self-checkout says there is an unexpected item in the bagging area, but the bag is empty.",
    "[Self-checkout assistance] I scanned this item twice by mistake. How do I remove one?",
    "[Self-checkout assistance] The machine is not recognising the barcode on these vegetables. What should I select?",
    "[Self-checkout assistance] I need to buy an age-restricted item. How do I request approval?",
    "[Self-checkout assistance] The card reader froze after I tapped my card. Has the payment gone through?",
    "[Self-checkout assistance] How do I apply my loyalty card at this self-checkout?",
    "[Self-checkout assistance] The machine says assistance is coming, but I have been waiting several minutes. Can someone help?",
    "[Self-checkout assistance] I brought my own bags. How do I stop the machine from treating them as unexpected items?",
    "[Self-checkout assistance] The price on the self-checkout is different from the shelf label. What should I do?",
    "[Self-checkout assistance] Can I split payment between cash and card at this self-checkout?",
    "[Payment problems] My card was declined here, but the banking app says there is enough money. What can I try?",
    "[Payment problems] The terminal charged me, but the till says the payment failed. Should I pay again?",
    "[Payment problems] Can I pay for this purchase using two different cards?",
    "[Payment problems] Do you accept contactless payment above £100 at this store?",
    "[Payment problems] My phone payment is not working. Can I enter the card manually?",
    "[Payment problems] Can I pay with cash at this checkout, or do I need to move to another till?",
    "[Payment problems] The cashier says my gift card has no balance, but I have never used it. Can you check?",
    "[Payment problems] Can I use a foreign-issued card to pay in this store?",
    "[Payment problems] The payment terminal offered to charge me in my home currency. Which option should I choose?",
    "[Payment problems] I was charged twice at the till. Who can verify the transactions before I leave?",
    "[Returns and exchanges] I bought this shirt in another branch. Can I return it here?",
    "[Returns and exchanges] I have the item and bank transaction but no paper receipt. Can I still get a refund?",
    "[Returns and exchanges] Can I exchange these shoes for another size without returning to the original store?",
    "[Returns and exchanges] This was a gift, and I do not want the buyer to be notified. What return options do I have?",
    "[Returns and exchanges] I opened the packaging but did not use the product. Can it still be returned?",
    "[Returns and exchanges] I paid partly with points. How would the refund be issued?",
    "[Returns and exchanges] The returns queue is very long. Can I start the process through the chatbot while I wait?",
    "[Returns and exchanges] Can I return a reduced item that turned out to be faulty?",
    "[Returns and exchanges] I bought this yesterday, but the price dropped today. Can I return and repurchase it?",
    "[Returns and exchanges] The product came with a free gift. Do I need to return both items?",
    "[Damaged or faulty products in store] This box is crushed. Can I get a discount or find an undamaged one?",
    "[Damaged or faulty products in store] The display lamp flickers when I switch it on. Is there another unit I can test?",
    "[Damaged or faulty products in store] This jar has a broken seal. Should I give it to a member of staff?",
    "[Damaged or faulty products in store] The zip on this jacket is already stuck. Can I try another one?",
    "[Damaged or faulty products in store] This television display has a line across the screen. Is that a problem with the model or just this unit?",
    "[Damaged or faulty products in store] The packaging is open, but the product looks unused. Is it being sold as new?",
    "[Damaged or faulty products in store] One piece is missing from this boxed set. Can someone check another box?",
    "[Damaged or faulty products in store] This toy has a loose part. Where should I report it so nobody else buys it?",
    "[Damaged or faulty products in store] The chair on display feels unstable. Can I test a boxed one before purchasing?",
    "[Damaged or faulty products in store] This bottle is leaking on the shelf. Can you alert staff and help me find a clean one?",
    "[Compatibility and specifications] Will this printer cartridge work with a Canon TS5150?",
    "[Compatibility and specifications] Is this phone case compatible with the iPhone 15 Pro or only the standard model?",
    "[Compatibility and specifications] Can this wall bracket support a 55-inch television weighing 18 kilograms?",
    "[Compatibility and specifications] Will this bulb work with a dimmer switch?",
    "[Compatibility and specifications] Is this cable suitable for connecting a laptop to a 4K monitor?",
    "[Compatibility and specifications] Will this replacement brush head fit an Oral-B Pro 3 toothbrush?",
    "[Compatibility and specifications] Can this memory card record 4K video without dropping frames?",
    "[Compatibility and specifications] Does this pan work on an induction hob?",
    "[Compatibility and specifications] Will this car seat fit a vehicle without ISOFIX points?",
    "[Compatibility and specifications] Is this smart plug compatible with Apple HomeKit?",
    "[Electronics demonstrations] Can I listen to these headphones before deciding which pair to buy?",
    "[Electronics demonstrations] Is there a way to test the camera zoom on this phone display model?",
    "[Electronics demonstrations] Can you show me how loud this Bluetooth speaker gets?",
    "[Electronics demonstrations] I want to compare the screens on these two laptops using the same video. Can that be arranged?",
    "[Electronics demonstrations] Can I try typing on this keyboard before buying it?",
    "[Electronics demonstrations] Is this television connected so I can see how sports look on it?",
    "[Electronics demonstrations] Can you demonstrate how quickly this tablet opens large documents?",
    "[Electronics demonstrations] Is there a sample photo from this instant camera I can look at?",
    "[Electronics demonstrations] Can I test whether this smartwatch interface is easy to read outdoors?",
    "[Electronics demonstrations] Could someone show me how the noise-cancelling modes work on these earbuds?",
    "[Home and furniture measurements] My space is 180 centimetres wide. Will this sofa fit with enough room to walk past?",
    "[Home and furniture measurements] Can this wardrobe be assembled in a room with a low ceiling?",
    "[Home and furniture measurements] What is the packaged size of this table so I know whether it will fit in my car?",
    "[Home and furniture measurements] How much clearance does this refrigerator need around the sides?",
    "[Home and furniture measurements] Would this rug be large enough to sit under a six-seat dining table?",
    "[Home and furniture measurements] Can the legs be removed from this armchair for delivery through a narrow doorway?",
    "[Home and furniture measurements] My mattress is 150 by 200 centimetres. Which fitted sheets here will fit it?",
    "[Home and furniture measurements] How far does this recliner extend when fully open?",
    "[Home and furniture measurements] Can this shelving unit be fixed safely to a plasterboard wall?",
    "[Home and furniture measurements] What is the maximum load for each shelf on this bookcase?",
    "[Beauty and skincare guidance] My skin is oily but sensitive. Which cleanser here would be the safest starting point?",
    "[Beauty and skincare guidance] Can you suggest a foundation shade close to the one I am currently wearing?",
    "[Beauty and skincare guidance] Which moisturiser would work under makeup without pilling?",
    "[Beauty and skincare guidance] I want a fragrance that is fresh rather than sweet. What should I test?",
    "[Beauty and skincare guidance] Can I use this exfoliating product if I already use retinol?",
    "[Beauty and skincare guidance] Which hair product would reduce frizz without making fine hair feel heavy?",
    "[Beauty and skincare guidance] I need sunscreen that does not leave a white cast. Which options should I try?",
    "[Beauty and skincare guidance] Can you suggest a lipstick with the same tone as this one but a matte finish?",
    "[Beauty and skincare guidance] Which shampoo here is suitable for colour-treated hair and a sensitive scalp?",
    "[Beauty and skincare guidance] Can I test this concealer shade hygienically before buying it?",
    "[Pharmacy and wellness retail] Which over-the-counter product is suitable for mild hay-fever symptoms?",
    "[Pharmacy and wellness retail] Can I take this cold medicine if I am already using an antihistamine?",
    "[Pharmacy and wellness retail] Where can I speak privately with the pharmacist about an emergency prescription?",
    "[Pharmacy and wellness retail] Which thermometer would be easiest to use for a young child?",
    "[Pharmacy and wellness retail] I need a wrist support for typing-related pain. How do I choose the right size?",
    "[Pharmacy and wellness retail] Is this pain-relief gel suitable for someone who cannot take ibuprofen tablets?",
    "[Pharmacy and wellness retail] Which rehydration product is appropriate after a stomach bug?",
    "[Pharmacy and wellness retail] Can you tell me whether this supplement needs to be taken with food?",
    "[Pharmacy and wellness retail] I am looking for compression socks for a long flight. Which level should I consider?",
    "[Pharmacy and wellness retail] Does the pharmacy offer blood-pressure checks without an appointment today?",
    "[Grocery substitutions] This recipe needs crème fraîche, but it is sold out. What can I use instead?",
    "[Grocery substitutions] I cannot find fresh basil. Which herb would be the closest substitute for pasta sauce?",
    "[Grocery substitutions] What could replace eggs in this cake recipe using products available here?",
    "[Grocery substitutions] This brand of baby formula is unavailable. Can you tell me whether switching brands is appropriate or whether I should speak to a pharmacist?",
    "[Grocery substitutions] I need a dairy-free substitute for double cream that will still whip.",
    "[Grocery substitutions] The recipe asks for bread flour, but only plain flour is left. What should I do?",
    "[Grocery substitutions] Which product could replace fish sauce in a vegetarian recipe?",
    "[Grocery substitutions] I cannot find the exact battery size listed. Is there a compatible alternative?",
    "[Grocery substitutions] The recommended printer ink is sold out. Is there a safe compatible version?",
    "[Grocery substitutions] Can you suggest a cheaper substitute for this ingredient without changing the flavour too much?",
    "[Sustainability and ethics] Which of these coffee brands has independently certified fair-trade sourcing?",
    "[Sustainability and ethics] Can you help me find laundry detergent sold in refillable packaging?",
    "[Sustainability and ethics] Which toilet paper here is made from recycled material?",
    "[Sustainability and ethics] Does this clothing brand publish information about factory working conditions?",
    "[Sustainability and ethics] Can I recycle this empty cosmetics container in the store?",
    "[Sustainability and ethics] Which of these fish products is certified as sustainably sourced?",
    "[Sustainability and ethics] Do you sell loose fruit and vegetables without plastic packaging?",
    "[Sustainability and ethics] Is this product locally made, or has it been imported?",
    "[Sustainability and ethics] Which phone case is made from recycled or biodegradable material?",
    "[Sustainability and ethics] Can I return used batteries or small electronics for recycling here?",
    "[Accessibility and mobility] I use a wheelchair. Is there a step-free route to the homeware department?",
    "[Accessibility and mobility] Where is the nearest accessible fitting room?",
    "[Accessibility and mobility] Can someone bring this product down from the top shelf for me?",
    "[Accessibility and mobility] Is there a quieter checkout area for customers who find busy queues overwhelming?",
    "[Accessibility and mobility] Do you have a shopping trolley designed to attach to a wheelchair?",
    "[Accessibility and mobility] Can the product information on this label be read aloud to me?",
    "[Accessibility and mobility] Where can I find a seat while the person with me finishes shopping?",
    "[Accessibility and mobility] Is there an induction loop at the customer-service desk?",
    "[Accessibility and mobility] Can I request assistance carrying my purchases to the car?",
    "[Accessibility and mobility] Which entrance is easiest to use with a mobility scooter?",
    "[Queues and staff assistance] The checkout queue is extremely long. Is another till likely to open soon?",
    "[Queues and staff assistance] I have been waiting at the electronics counter for fifteen minutes. Can you request a staff member?",
    "[Queues and staff assistance] Is there a faster checkout option for only two items?",
    "[Queues and staff assistance] Can I reserve my place in the returns queue through the chatbot?",
    "[Queues and staff assistance] The fitting-room attendant is not here. Can someone unlock a room?",
    "[Queues and staff assistance] I need expert advice about this appliance. Which staff member should I ask for?",
    "[Queues and staff assistance] Can you tell me whether the service desk is still open?",
    "[Queues and staff assistance] I pressed the assistance button in the aisle, but nobody has arrived. Can you send another request?",
    "[Queues and staff assistance] Is there a queue for the pharmacy consultation room right now?",
    "[Queues and staff assistance] Can someone meet me in the furniture section to discuss delivery options?",
    "[Click and collect] I’m at the collection point, but the locker code is not working.",
    "[Click and collect] My order says ready for collection. Which desk should I go to?",
    "[Click and collect] Can someone bring my click-and-collect order to the car park?",
    "[Click and collect] The package I collected contains the wrong item. Can I exchange it before leaving?",
    "[Click and collect] My collection email says photo ID is required, but I only have the payment card. What can I do?",
    "[Click and collect] I am collecting an order for someone else. Which documents do I need?",
    "[Click and collect] The order is marked collected in the app, but I have not received it. Can you check?",
    "[Click and collect] Can I add another in-store item to my collection order before paying?",
    "[Click and collect] I arrived just before closing. Will the collection desk still release my order?",
    "[Click and collect] The item is too large for my car. Can I change the collection to home delivery?",
    "[Gift shopping] I need a birthday gift for a colleague I do not know very well. What is a safe choice under £25?",
    "[Gift shopping] Can you suggest a gift for a ten-year-old who likes science?",
    "[Gift shopping] I need something small that can fit in hand luggage. What would you recommend?",
    "[Gift shopping] Which of these gift sets is suitable for someone with sensitive skin?",
    "[Gift shopping] Can you help me find a wedding gift that does not require knowing the couple’s home style?",
    "[Gift shopping] I want a thoughtful gift for someone who has just moved house. What could I buy here?",
    "[Gift shopping] Can this item be gift-wrapped in store today?",
    "[Gift shopping] I need a last-minute present for a vegetarian food lover. What are my options?",
    "[Gift shopping] Which toys here are suitable for a child aged three to four?",
    "[Gift shopping] Can the recipient exchange this gift without seeing the price I paid?",
    "[Store services] Do you offer trouser alterations in this branch, and how long do they take?",
    "[Store services] Can this bicycle be assembled before I collect it?",
    "[Store services] Is same-day home delivery available for this sofa?",
    "[Store services] Can someone install this child car seat after I purchase it?",
    "[Store services] Do you cut keys in this store?",
    "[Store services] Can the curtains be shortened to a custom length?",
    "[Store services] Is there a service to transfer data from my old phone to a new one today?",
    "[Store services] Can I book an eye test while I am already in the store?",
    "[Store services] Do you offer engraving on items purchased here?",
    "[Store services] Can this large appliance be delivered and the old one removed?",
    "[Receipts, bags and security] The security alarm went off when I left the checkout, but I paid for everything. What should I do?",
    "[Receipts, bags and security] I declined a paper receipt, but now I need one. Can it be reprinted?",
    "[Receipts, bags and security] The cashier forgot to remove the security tag from this jacket. Where can I get it removed?",
    "[Receipts, bags and security] I was charged for a carrier bag that I did not receive. Can this be corrected?",
    "[Receipts, bags and security] The receipt lists an item I did not buy. Can someone check the transaction before I leave?",
    "[Receipts, bags and security] Can I have a digital receipt sent to a different email address?",
    "[Receipts, bags and security] The cashier placed a fragile item in the same bag as heavy tins. Can I get another bag?",
    "[Receipts, bags and security] I left my shopping bag at the till a few minutes ago. Has it been handed in?",
    "[Receipts, bags and security] The receipt is too faded to read. Can you retrieve the purchase using my card?",
    "[Receipts, bags and security] A security guard stopped me even though I used self-checkout correctly. Who can review what happened?",
    "[In-store complaints] The promotional display blocks the accessible route through this aisle. Can someone move it?",
    "[In-store complaints] The changing room is dirty and there are clothes all over the floor. Can staff be notified?",
    "[In-store complaints] I found several refrigerated products left on a normal shelf. Can you alert someone?",
    "[In-store complaints] The music in this section is painfully loud. Is there a quieter area where I can shop?",
    "[In-store complaints] A price label appears deliberately placed under the wrong product. Can someone verify it?",
    "[In-store complaints] I have asked two staff members for help and both sent me to different departments. Who can actually resolve this?",
    "[In-store complaints] There is broken glass near the drinks aisle. Can you report it immediately?",
    "[In-store complaints] The lift has stopped working, and I cannot reach the floor I need. What assistance is available?",
    "[In-store complaints] The store is closing early, but the website still shows the normal hours. Can I complete my purchase?",
    "[In-store complaints] I was spoken to rudely at the service desk. How can I report the interaction while I am still here?",
]
